### ISSUE TITLE
blog post review

### ISSUE THREAD

**Issue by raynamharris** [datacarpentry/python-ecology-lesson-es#62]
Hello! I've drafted a blog post describing the process of translating the translating the Python lesson. Yay! https://github.com/carpentries/carpentries.org/pull/349

I've listed everyone who contributed and the country where they live. If you could look over it and make sure I have your information correct, that would be great. 

Also, feel free to let me know if you would like to be left anonymous or if you have any suggestions or concerns. Thanks! 

@monialo2000 @LauCIFASIS @arredondo23 @jmbarrios @miguelgondu @fergarciafer @agbeltran @spencerbh @rzayas @welozano @orchid00 @ComplejoC @fmichonneau @nohemihuanca @enricescorsa @NPalopoli @spereyra @Helysalgado @chekos @LUS24 @trallard @maxim-belkin @wrightaprilm @charlesreid1

**Comment by wrightaprilm** [comment]
Completely forgot to give you feedback, but I just looked at the website version. Looks great! Awesome work, @raynamharris!

**Comment by raynamharris** [comment]
Thanks everyone for feedback. It’s posted here! https://carpentries.org/blog/2019/01/python-ecology-es/

**Comment by monialo2000** [comment]
Thank you Rayna!!! Sorry, I can't see it. But thank you for all!  :)

**Comment by spereyra** [comment]
Great post Rayna!!!! Thank you
Congrats to all translators!

**Comment by welozano** [comment]
Thank you Rayna.
I am available to keep helping with this efforts.

Regards.

Wilson

________________________________
