### ISSUE TITLE
Add key points to six episodes

### ISSUE THREAD

**Issue by raynamharris** [datacarpentry/python-ecology-lesson-es#66]
These episodes are missing key points. For some episodes, key points can be translated from the English source code. 

- [x] Breve introducción a la Programación en Python, [website](https://datacarpentry.org/python-ecology-lesson-es/01-short-introduction-to-Python/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/01-short-introduction-to-Python.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/01-short-introduction-to-Python.md)
- [x] Comenzando con datos, [website](https://datacarpentry.org/python-ecology-lesson/02-starting-with-data/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/02-starting-with-data.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/02-starting-with-data.md)
- [x] Tipos de datos y formatos, [website](https://datacarpentry.org/python-ecology-lesson/04-data-types-and-format/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/04-data-types-and-format.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/04-data-types-and-format.md)
- [x] Combinando DataFrames con Pandas, [website](https://datacarpentry.org/python-ecology-lesson/04-data-types-and-format/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/04-data-types-and-format.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/04-data-types-and-format.md)
- [x] Combinando DataFrames con Pandas, [website](https://datacarpentry.org/python-ecology-lesson/05-merging-data/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/05-merging-data.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/05-merging-data.md)
- [x] Flujos de trabajo y automatización, [website](https://datacarpentry.org/python-ecology-lesson/06-loops-and-functions/index.html), [source-es](https://github.com/datacarpentry/python-ecology-lesson-es/blob/gh-pages/_episodes/06-loops-and-functions.md), [source-en](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/06-loops-and-functions.md)

Relates to #63

**Comment by map0logo** [comment]
Hi! I solved this issue. 4 days ago.

**Comment by orchid00** [comment]
added to https://datacarpentry.org/python-ecology-lesson-es/05-merging-data/index.html los otros episodios todavia no tienen "Puntos clave"

**Comment by jjhsaq** [comment]
Hola, me gustaría contribuir con la traducción, ¿como puedo ayudar?

I'd like to help with translations, how can I help?

**Comment by raynamharris** [comment]
The key points on these episode have been updated in the yaml heading of each episode, but they aren't appearing on the rendered website. Any ideas how to fix this? @fmichonneau

**Comment by vinisalazar** [comment]
Hello, this seems to be fixed; the website is rendering the key points. I'll close this issue after a few days if no one objects.

**Comment by iramosp** [comment]
Hi, following up on the previous comment, I'll close the issue since the key points are rendered.
