### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/python-ecology-lesson-es#77]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by iramosp** [comment]
Hi @annajiat, thanks for this suggestion.
This issue, along with other style improvements, will be addressed in an upcoming redesign of the lesson infrastructure. You can learn more about it here: https://carpentries.org/blog/2022/01/live-lesson-infrastructure/. So, I'll close this issue for now.
